import { ANIMATION_TYPES } from '../../../../../shared/constants/timeline';

export const EMOJI_PALETTE = ['⚡', '💸', '🚀', '✨', '🤖', '👑', '💥', '❤️', '🎯', '💡', '💎'];

export const ANIMATION_OPTIONS_15 = [
  { id: ANIMATION_TYPES.POP, name: 'Pop Scale' },
  { id: ANIMATION_TYPES.BOUNCE, name: 'Spring Bounce' },
  { id: ANIMATION_TYPES.STREAMING, name: 'Karaoke Streaming' },
  { id: ANIMATION_TYPES.KARAOKE_SWEEP, name: 'Gradient Sweep Fill' },
  { id: ANIMATION_TYPES.TYPEWRITER, name: 'Typewriter Letter Reveal' },
  { id: ANIMATION_TYPES.ELASTIC_SPRING, name: 'Elastic Spring Rebound' },
  { id: ANIMATION_TYPES.CHROMATIC_GLITCH, name: 'RGB 3D Channel Glitch' },
  { id: ANIMATION_TYPES.ZOOM_IN, name: 'Rapid Zoom In (0.3x -> 1.3x)' },
  { id: ANIMATION_TYPES.ZOOM_OUT, name: 'Elastic Zoom Out' },
  { id: ANIMATION_TYPES.SLIDE_UP, name: 'Velocity Slide Up' },
  { id: ANIMATION_TYPES.SLIDE_DOWN, name: 'Velocity Slide Down' },
  { id: ANIMATION_TYPES.SLIDE_LEFT, name: 'Horizontal Slide Left' },
  { id: ANIMATION_TYPES.SLIDE_RIGHT, name: 'Horizontal Slide Right' },
  { id: ANIMATION_TYPES.SPIN_REVEAL, name: '360° Spin Reveal' },
  { id: ANIMATION_TYPES.FLIP_ROTATE, name: '3D Tilt Angle Flip' },
  { id: ANIMATION_TYPES.NEON_AURA, name: 'Pulsating Neon Aura' },
  { id: ANIMATION_TYPES.SHAKE_RUMBLE, name: 'Earthquake Jitter' },
  { id: ANIMATION_TYPES.FLOATING, name: 'Sinusoidal Floating Wave' },
  { id: ANIMATION_TYPES.WAVE, name: 'Sine Wave Oscillation' },
  { id: ANIMATION_TYPES.GLOW_PULSE, name: 'Soft Glow Pulse' },
  { id: ANIMATION_TYPES.SINGLE_FLASH, name: 'Strobe Flash Onset' },
  { id: ANIMATION_TYPES.EXPAND_BLUR, name: 'Focus Blur-to-Sharp' },
  { id: ANIMATION_TYPES.SPIRAL_IN, name: 'Vortex Spiral Entrance' },
  { id: ANIMATION_TYPES.DROP_BOUNCE, name: 'Gravity Drop Bounce' },
  { id: ANIMATION_TYPES.HEARTBEAT, name: 'Rhythm Heartbeat Pulse' },
  { id: ANIMATION_TYPES.RUBBER_BAND, name: 'Rubberband Stretch Squeeze' },
  { id: ANIMATION_TYPES.SWING_PENDULUM, name: 'Pendulum Swing' },
  { id: ANIMATION_TYPES.JELLO_WOBBLE, name: 'Jello Wobble' },
  { id: ANIMATION_TYPES.FADE_GLIDE, name: 'Smooth Opacity Glide' },
  { id: ANIMATION_TYPES.OVERSHOOT_SCALE, name: 'Explosive Overshoot Scale' },
  { id: ANIMATION_TYPES.SKEDADDLE, name: 'Slanted Fast Glide' },
  { id: ANIMATION_TYPES.ORBIT_ROTATION, name: 'Elliptical Orbit Sway' },
  { id: ANIMATION_TYPES.LIGHT_BEAM, name: 'Laser Beam Sweep' },
  { id: ANIMATION_TYPES.DUAL_BOUNCE, name: 'Double Impact Bounce' },
  { id: ANIMATION_TYPES.FLOAT_UP, name: 'Gentle Float Drift' },
  { id: ANIMATION_TYPES.SLANTED_SHAKE, name: 'Diagonal Slant Jitter' },
  { id: ANIMATION_TYPES.PULSE_ZOOM, name: 'Rhythm Pulse Zoom' },
  { id: ANIMATION_TYPES.SPLIT_FLIP, name: 'Horizontal Split Flip' },
  { id: ANIMATION_TYPES.WOBBLE_TOP, name: 'Top Pin Wobble' },
  { id: ANIMATION_TYPES.SPRING_REBOUND, name: 'Tight Mechanical Spring' },
  { id: ANIMATION_TYPES.MAGNIFY_POP, name: 'Lens Magnifier Pop' },
  { id: ANIMATION_TYPES.STAGGER_DROP, name: 'Cascading Stagger Drop' },
  { id: ANIMATION_TYPES.RIPPLE_WAVE, name: 'Concentric Ripple Wave' },
  { id: ANIMATION_TYPES.SHADOW_BURST, name: 'Shadow Burst Explosion' },
  { id: ANIMATION_TYPES.SHUTTER_SNAP, name: 'Shutter Snap Zoom' },
  { id: ANIMATION_TYPES.ELEVATOR_RISE, name: 'High-Speed Elevator Rise' },
  { id: ANIMATION_TYPES.CYBER_PULSE, name: 'Cyberpunk Strobe Pulse' },
  { id: ANIMATION_TYPES.TILT_SWAY, name: 'Dynamic Tilt Sway' },
  { id: ANIMATION_TYPES.BOUNCE_IN_UP, name: 'Spring Bounce In Up' },
  { id: ANIMATION_TYPES.FLICKER_GLOW, name: 'Neon Lamp Flicker' },
  { id: ANIMATION_TYPES.NONE, name: 'Static Clean' },
];
